User-agent: *
Crawl-delay: 2
Request-rate: 2/3
Visit-time: 0800-1600
Disallow: /project/pylonshq*rev=*
Disallow: /project/pylonshq*format=*
Disallow: /project/pylonshq/query
Disallow: /project/pylonshq/search
Disallow: /project/pylonshq/wiki
Disallow: /project/pylonshq/newticket
Disallow: /project/pylonshq/changeset
Disallow: /project/pylonshq/log
Disallow: /project/pylonshq/milestone
Disallow: /project/pylonshq/timeline
Disallow: /project/pylonshq/roadmap
